import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { WorkspaceDatabase, type CreatedRunContext } from '../src/main/database';
import { ExecutorManager } from '../src/main/executorManager';
import { BealeToolRouter } from '../src/main/openaiTools';

const createdDirs: string[] = [];
const ENV_KEYS = ['BEALE_VMCTL_COMMAND', 'BEALE_VMCTL_ARGS_JSON', 'BEALE_VMCTL_TIMEOUT_MS'];
let callSequence = 0;

afterEach(() => {
  for (const key of ENV_KEYS) {
    delete process.env[key];
  }
  callSequence = 0;
  for (const dir of createdDirs.splice(0)) {
    rmSync(dir, { recursive: true, force: true });
  }
});

describe('structured research tools', () => {
  it('searches scoped source and binary-derived strings, then reads bounded source chunks', () => {
    const { db, context, sourceFile, binaryFile } = openStructuredToolDb();
    const router = new BealeToolRouter(db);

    const search = callTool(router, context, 'search', { query: 'authorization boundary', target: '' });
    expect(search.status).toBe('success');
    expect(JSON.stringify(search.payload)).toContain(sourceFile);

    const binarySearch = callTool(router, context, 'search', { query: 'CRASH_SIG', target: '' });
    expect(binarySearch.status).toBe('success');
    expect(JSON.stringify(binarySearch.payload)).toContain(binaryFile);
    expect(JSON.stringify(binarySearch.payload)).toContain('binaryDerived');

    const read = callTool(router, context, 'code_browser', { path: sourceFile, symbol: 'check_access' });
    expect(read.status).toBe('success');
    expect(JSON.stringify(read.payload)).toContain('check_access');
    expect(JSON.stringify(read.payload)).toContain('authorization boundary');

    const blocked = callTool(router, context, 'code_browser', { path: join(tmpdir(), 'out-of-scope.c'), symbol: '' });
    expect(blocked.status).toBe('policy_blocked');
    expect(JSON.stringify(blocked.payload)).toContain('path_outside_active_scope');
    db.close();
  });

  it('preserves model-generated artifacts separately from observations and gates verifier promotion on evidence references', () => {
    const { db, context } = openStructuredToolDb();
    const router = new BealeToolRouter(db);

    const artifact = callTool(router, context, 'artifact', {
      name: 'candidate-poc.txt',
      content: 'candidate input generated by model',
      kind: 'poc_input'
    });
    expect(artifact.status).toBe('success');
    expect(artifact.artifact_id).toBeTruthy();
    expect(artifact.payload.observationBacked).toBe(false);

    const verifier = callTool(router, context, 'verifier', {
      hypothesis: 'candidate parser issue',
      expectation: 'candidate input should reproduce the observed condition',
      artifact_id: artifact.artifact_id,
      trace_event_id: artifact.trace_event_id
    });
    expect(verifier.status).toBe('success');
    expect(verifier.payload.status).toBe('inconclusive');
    expect(verifier.payload.promotedFinding).toBe(false);
    expect((verifier.payload.evidenceReferences as { artifactId: string }).artifactId).toBe(artifact.artifact_id);

    const detail = db.getRunDetail(context.run.id);
    expect(detail.artifacts.find((candidate) => candidate.id === artifact.artifact_id)?.source).toBe('model_generated');
    expect(detail.verifierRuns).toHaveLength(1);
    expect(detail.traceEvents.some((event) => event.type === 'verifier_result' && event.source === 'verifier')).toBe(true);
    db.close();
  });

  it('runs Python and the debugger wrapper through the disposable VM controller boundary', () => {
    const { db, context, logPath } = openStructuredToolDb();
    configureVmctlFixture(logPath);
    const router = new BealeToolRouter(db, new ExecutorManager(db));

    const python = callTool(router, context, 'python', {
      task: 'generate a candidate input',
      script: 'print("candidate")',
      artifact_path: '/tmp/beale-output.txt'
    });
    expect(python.status).toBe('success');
    expect(python.artifact_id).toBeTruthy();
    expect(python.payload.hostExecution).toBe(false);

    const debuggerResult = callTool(router, context, 'debugger', {
      operation: 'gdb_probe',
      target: '/workspace/target',
      input_path: ''
    });
    expect(debuggerResult.status).toBe('success');
    expect(debuggerResult.payload.wrapper).toBe('gdb_batch_probe');
    expect(debuggerResult.payload.hostExecution).toBe(false);

    const actions = readVmctlEntries(logPath).map((entry) => entry.input.action);
    expect(actions).toContain('create_context');
    expect(actions).toContain('clone_context');
    expect(actions).toContain('import_workspace_material');
    expect(actions.filter((action) => action === 'execute')).toHaveLength(2);
    expect(actions).toContain('export_artifact');
    expect(actions.filter((action) => action === 'destroy')).toHaveLength(2);

    const operations = readVmctlEntries(logPath)
      .filter((entry) => entry.input.action === 'execute' && entry.input.payload.operation)
      .map((entry) => entry.input.payload.operation?.operationKind);
    expect(operations).toEqual(['python', 'shell']);
    db.close();
  });
});

interface ToolOutput {
  status: string;
  summary: string;
  trace_event_id?: string;
  artifact_id?: string;
  payload: Record<string, unknown>;
}

function callTool(router: BealeToolRouter, context: CreatedRunContext, name: string, args: Record<string, unknown>): ToolOutput {
  return JSON.parse(
    router.execute(context, {
      callId: `call_${name}_${(callSequence += 1)}`,
      name,
      argumentsJson: JSON.stringify(args)
    }).output
  ) as ToolOutput;
}

function openStructuredToolDb(): { db: WorkspaceDatabase; context: CreatedRunContext; sourceFile: string; binaryFile: string; logPath: string } {
  const dir = mkdtempSync(join(tmpdir(), 'beale-structured-tools-'));
  createdDirs.push(dir);
  const artifactRoot = join(dir, '.beale', 'artifacts');
  const targetDir = join(dir, 'target');
  mkdirSync(join(artifactRoot, 'sha256'), { recursive: true });
  mkdirSync(join(targetDir, 'src'), { recursive: true });
  mkdirSync(join(targetDir, 'bin'), { recursive: true });

  const sourceFile = join(targetDir, 'src', 'access.c');
  const binaryFile = join(targetDir, 'bin', 'target.bin');
  const logPath = join(dir, 'vmctl.log');
  writeFileSync(sourceFile, 'int check_access(void) {\n  // authorization boundary\n  return 1;\n}\n');
  writeFileSync(binaryFile, Buffer.from([0, 1, 2, ...Buffer.from('CRASH_SIG_NEAR_PARSE', 'utf8'), 0, 3]));

  const db = new WorkspaceDatabase(join(dir, '.beale', 'beale.sqlite'), artifactRoot);
  db.initialize();
  db.saveProgramScope({
    programName: 'Structured Tool Program',
    organizationName: 'Example Org',
    descriptionMarkdown: 'Scoped structured tool test.',
    rulesMarkdown: 'Offline guest execution only.',
    networkProfile: 'offline',
    expiresAt: null,
    assets: [{ direction: 'in_scope', kind: 'path', value: targetDir, sensitivity: 'internal', attributes: {} }]
  });
  const context = db.createRun({
    scopeVersionId: db.getActiveScope().id,
    title: 'Structured tool smoke',
    promptMarkdown: '# Structured tool smoke',
    mode: 'open_discovery',
    model: 'gpt-5.5',
    reasoningEffort: 'xhigh',
    attemptStrategy: 'single_path',
    networkProfile: 'offline',
    sandboxProfile: 'local_disposable_vm',
    budget: { maxMinutes: 5, maxAttempts: 1, maxCostUsd: 0, runEngine: 'openai_responses' }
  });
  return { db, context, sourceFile, binaryFile, logPath };
}

function configureVmctlFixture(logPath: string): void {
  process.env.BEALE_VMCTL_COMMAND = process.execPath;
  process.env.BEALE_VMCTL_ARGS_JSON = JSON.stringify([join(process.cwd(), 'tests/fixtures/vmctl-fixture.mjs'), logPath]);
}

function readVmctlEntries(logPath: string): Array<{ input: { action: string; payload: { operation?: { operationKind: string } } } }> {
  const content = readFileSync(logPath, 'utf8').trim();
  if (!content) return [];
  return content.split('\n').map((line) => JSON.parse(line) as { input: { action: string; payload: { operation?: { operationKind: string } } } });
}
