export const IPC_CHANNELS = {
  selectWorkspace: 'beale:select-workspace',
  selectProgramDirectory: 'beale:select-program-directory',
  getProgramRegistry: 'beale:get-program-registry',
  lookupHackerOneProgram: 'beale:lookup-hackerone-program',
  createProgram: 'beale:create-program',
  openProgram: 'beale:open-program',
  removeProgram: 'beale:remove-program',
  openWorkspace: 'beale:open-workspace',
  createWorkspace: 'beale:create-workspace',
  getSnapshot: 'beale:get-snapshot',
  getHostEnvironment: 'beale:get-host-environment',
  getOpenAiStatus: 'beale:get-openai-status',
  startOpenAiOAuth: 'beale:start-openai-oauth',
  refreshOpenAiStatus: 'beale:refresh-openai-status',
  saveProgramScope: 'beale:save-program-scope',
  startRun: 'beale:start-run',
  runBenchmarkSuite: 'beale:run-benchmark-suite',
  exportWorkspaceBackup: 'beale:export-workspace-backup',
  getRunDetail: 'beale:get-run-detail',
  steerRun: 'beale:steer-run',
  programRegistryUpdated: 'beale:program-registry-updated',
  snapshotUpdated: 'beale:snapshot-updated'
} as const;
